model: "resnet_estimator"
env_variables:
  TF_PRELIMINARY_CLUSTER_SIZE: 150
  TF_SHRINK_CLUSTER_CONTROL_DEPENDENCY: 1

parameters:
  max_train_steps: 200
  batch_size: 128
  resnet_size: 50
  data_dir: "/software/data/tf/data/imagenet/tfrecords"
  num_gpus: 1
  distribution_strategy: "off"
  data_format: "channels_last"
  save_checkpoint_steps: 200
  train_epochs: 1
  model_dir: "/tmp/resnet_estimator"
  display_steps: 1
  experimental_preloading: 1
  use_horovod: true
  use_train_and_evaluate: false
  epochs_between_evals: 1
  enable_lars: false
  dummy_epoch: false
  disable_eval: true
  hls_type: "HLS1"
  num_workers_per_hls: 8
