model: "resnet_keras"

env_variables:
  TF_PRELIMINARY_CLUSTER_SIZE: 20
  TF_PRELIMINARY_CLUSTER_SIZE_THRESHOLD: 700
  HABANA_USE_PREALLOC_BUFFER_FOR_ALLREDUCE: "false" # ART:ON by default
  TF_ENABLE_BF16_CONVERSION: 1
  TF_ALLOW_CONTROL_EDGES_IN_HABANA_OPS: 1
  HABANA_USE_STREAMS_FOR_HCL: "true"
  USE_LARS_OPTIMIZER: 1
  TF_RECIPE_CACHE_PATH: "/tmp/resnet_keras_lars"

parameters:
  data_dir: "/root/tensorflow_datasets/imagenet/tf_records"
  batch_size: 256
  steps_per_loop: 100
  log_steps: 100
  model_dir: "/tmp/resnet_keras_lars/"
  data_format: "channels_last"
  train_epochs: 90
  experimental_preloading: 1
  enable_checkpoint_and_export: false
  enable_tensorboard: false
  epochs_between_evals: 8
  use_horovod: true
  optimizer: "SGD"
  lr_schedule: "piecewise"
  data_loader_image_type: "bf16"
  weight_decay: 0.0001
  warmup_epochs: 5
  distribution_strategy: "off"
  num_gpus: 0
  num_workers_per_hls: 8
  hls_type: "HLS1"